### ISSUE TITLE
Drugged ammo causes golem boss to rapidly fire his fists (possible fix included)

### ISSUE THREAD

**Issue by direwolf420** [Muzuwi/AmmoboxPlus#1]
# **Environment**
 - Terraria version: 1.3.5.2
 - tModLoader Version: 0.10.1.5
 - Ammobox Version: 1.4.4.1
 - Present mods (if applicable): should be independent

# **Description**
Since golems fists leash out based on a timer, them having the drugged debuff causes the body of the golem boss (which is naturally flagged with npc.dontTakeDamage = false) lose life, with then causes the firsts to leash out about 8 times as frequent

# **Steps To Reproduce**
Shoot golem fists or the head with drugged arrows/bullets

# **Expected behavior**
It really is an issue in vanilla code and how drugged interacts with NPCs, see Additional context

# **Additional context**
https://github.com/Muzuwi/AmmoboxPlus/blob/master/AmmoboxGlobalNPC.cs#L218, around here needs to be a check if the NPC n is of type GolemBody, or a check for !n.dontTakeDamage

GolemFist AI
```
if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
{
      num691 += 8f; //timer gets incremented 8 times as fast because of this
}

**Comment by Muzuwi** [comment]
Thanks for the report, I'll see about fixing it for the next update
