### ISSUE TITLE
Starfall ammo causes self inflicted damage

### ISSUE THREAD

**Issue by mtjscape** [Muzuwi/AmmoboxPlus#2]
# **Environment**
 - Terraria version: 1.3.5.2
 - tModLoader Version: 0.10.1.5
 - Ammobox Version: 1.4.4.1
 - Present mods (if applicable): The issue should be independent of other mods

# **Description**
Starfall Bullet's "piercing star" effect can damage the player, much like a regular falling star can. Testing most vanilla guns has shown the star damages the player even when stationary. Upon testing, the dart and rocket variants also cause damage to the player. This renders the ammunition type almost unusable.

# **Steps To Reproduce**
Use Starfall/burst ammo with weapons that do not modify the ammo type. Movement does not seem to help avoid player damage.

# **Expected behavior**
A comparison could be made with the star cannon, which does not damage the player.

# **Additional context**
In your code, you change the projectile type upon projectile spawn with:
`Projectile.NewProjectile(pos, vel, ProjectileID.FallingStar, 40, 0, own);`

I am not sure if this calls for the same projectile type as the Star Cannon, which looking at the source code for Terraria items, seems to be "this.shoot = 12," which matches the following :
```
if (this.type == 12) { 
      this.name = "Falling Star";  
      this.width = 16;  
      this.height = 16;  
      this.aiStyle = 5;  
      this.friendly = true;  
      this.penetrate = -1;  
      this.alpha = 50;  
      this.light = 1f;  
}
```
I am not sure if the "friendly" boolean tells the game if the projectile can harm the player, but it might be a good first place to look. Your ammunition could be shooting non-friendly falling stars.

**Comment by Muzuwi** [comment]
Thanks for reporting. Unfortunately, I cannot reproduce this on my end; stars from bullets/rockets don't damage the player. Could you try again but in a minimal testing setup with no other mods present (if it wasn't done in one)? Additionally, does this affect singleplayer, multiplayer, or both?

**Comment by mtjscape** [comment]
Oh I just ran through them, made an obvious discovery, I had Fargo's Soul mod on. Forgot about masochist mode  and upon disabling it the starfall ammo is working fine, It seems the mod causes regular falling stars to harm players.
Thanks for the quick reply, feeling silly since I totally forgot I had the mode enabled.

**Comment by Muzuwi** [comment]
Good to know, happens to the best of us.
