### ISSUE TITLE
Endless Ammo is consumed by OmniTurret from MechTransfer

### ISSUE THREAD

**Issue by LucoEldritch** [Muzuwi/AmmoboxPlus#3]
# **Environment**
 - Terraria version: 1.3.5.2 (Windows)
 - tModLoader Version: 0.10.1.5
 - Ammobox Version: 1.4.4.1
 - Present mods (if applicable): MechTransfer (v1.6.2)

# **Description**
Endless variants of Ammo, like Endless Miner's Magazine and various others (probably all) are being consumed when used with MechTransfer turrets.

# **Steps To Reproduce**

1. Play with MechTransfer and AmmoBoxPlus
2. Get any Endless ammo variant
3. Place in a chest
4. Place a Transfer extractor near the chest
5. Place a Transfer injector near the extractor (but not near the chest)
6. Place an Omni Turret near the Transfer injector
7. Wire something to the Transfer Extractor
8. Place the Endless ammo variant (step 1) into chest
9. When the wire is activated, the item is consumed

# **Expected behavior**
The Endless ammo should not be consumed by Omni turret

# **Screenshots**
Example set-up (steps 3-6)
![image](https://user-images.githubusercontent.com/35275945/53297169-e252b900-37f8-11e9-9938-4499c44fe1b9.png)

# **Additional context**
The issue is because in their code, ConsumeAmmo is ignored, and instead, it's only checked if item.Consumable is true or not. If true, the ammo is consumed.
This can be checked in [this file](https://github.com/DRKV333/MechTransfer/blob/master/ContainerAdapters/OmniTurretAdapter.cs), lines 81-82:
```C#
            if (item.consumable)
                item.stack--;
```

I compared with the code of [Lolkat Infinity](https://github.com/Lolkat76/infinity/blob/master/Items/Ammo/EndlessBlueFlare.cs), and noticed that instead of overriding ConsumeAmmo, the item is never made consumable to begin with -- and considering that MechTransfer's turrets work with vanilla ammo (edit: vanilla _endless_ ammo), I figured out that this should be the default/same way it's done in the game, so I figured it should be fixed here, not in MechTransfer.

_If the issue is not closed by then, I'll try to make a Pull Request later (even knowing the issue could end being closed afterwards)._

**Comment by LucoEldritch** [comment]
# More Info
Sadly, I couldn't test after the changes because of missing textures, but I made the changes anyway. 
**I also changed rockets, despite they being not used with MechTransfer Turrets.**

The **Pull Request** is at #4 , but I messed up, I didn't notice that this version is 1.5.0.0, I should've cloned from 1.4.4.1. Well, I've left it anyway, if you need me to do it from 1.4.4.1, let me know and I can fix it.

# Test World
I've made a world to test those changes. My idea is have an area to test all ammo (normal variant and endless variants) with both **weapons and omni turrets**
- When you join, there'll be five chests and a Teleporter. The chests are the following:
 - The first chest has 4 basic weapons (Rocket Launcher, Blowpipe, Wooden Bow and Musket), to test the weapons.
 - Second Chest has all **arrow**, then all **bullets**, from the AmmoBoxPlus, alphabetically.
 - Third Chest has **darts** and **rockets**.
 - Fourth Chest is the same as Second Chest, Arrows and Bullets, but Endless version
 - Fifth Chest is Endless darts and rockets.
- The area to the left is to shot rockets without damaging yourself. **Important**, avoid shooting the Miner's Rocket to the right, as this could damage the area of testing from the turret.
- Using the teleporter with the Lever will teleport to an area with 9 (10) chests, and two switches: a red one, and a blue one.
- The first chest (up one) has Endless darts and rockets
- The second chest (to the right) has Endless arrows and bullets (with Ankh shields in the first space, and filling empty spaces, to avoid messing the order of the items. I used Ankh shields because they're easily distinguishable).
- Below them is the same, but with consumable variants
- And there's a chest next to the turret. This one will only be used while the turret is firing.
- When the **red switch** is pressed:
 - The first item transfered will be the first Ankh shield. Then, the first items from the first chest will be pushed to the second chest, and become the new first item of the second chest. This item will become the first, so, it'll become the next item to be used.
 - Because of this, the order is: *Darts, Rockets¹, Arrows and Bullets* (¹Rockets won't be fired because OmniTurrets don't fire those, it's intentional).
 - The ammo is shot **4 times**, then is pushed to the chests in the far right _(sadly, I couldn't figure out an easy way to sort them there)_.
 - _The blackened chest is there only to filter Ankh Shields_.
- When the **blue switch** is pressed:
 - The same process as above happens, but it'll change between feeding Endless and Consumable ammo.
- **In the end, the expected is:** all Endless variants reach the destiny, all Consumable Arrows, Darts and Bullets ends with 995 in the Stack, and all Consumable Rockets end with 999 in the Stack.
- This process takes 46 (number of different ammo) x 5 seconds, about 225 seconds, or 4 minutes. This is only to one test; pressing the blue switch and testing the other type will take 4 more minutes.

Just to mention, the exactly mods used in this test was: AmmoBox+ 1.4.4.1, MechTransfer 1.6.2 and Cheat Sheet 0.5.0.2, that I used to gather all those items.

Here's the file: [AmmoBoxPlusTesterWorld.zip](https://github.com/Muzuwi/AmmoboxPlus/files/2898786/AmmoBoxPlusTesterWorld.zip)

**Edit: If you make the changes and send me the .tmod file, I would gladly test it.**

**Comment by Muzuwi** [comment]
Wow, thanks for the in-depth analysis and the PR. I'll merge it to master soon(ish) after testing (thanks for that test world, by the way!)

**Comment by LucoEldritch** [comment]
No problem, glad to help, and thanks for the great mod
